In [2]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print('x:\n{}'.format(x))

x:
[[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np
from scipy import sparse
#Create a 2d array with diagonal of 1s and 0s elsewhere
eye = np.eye(4)
print("NumPy array:\n{}".format(eye))

NumPy array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
