<a href="https://colab.research.google.com/github/saim963/LabWorkSem3Python/blob/main/week5_q5_collab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 6- Write a create a numpy array and sort as per cases:
######a. Case1: Sort the array by the second row.
######b. Case2: Sort the array by the second column.

In [ ]:
import numpy as np
arr = np.random.randint(1,10,(5,5))
print(f'Original Array: \n{arr}')

# sort by 2nd row
sort_row = arr[1,:].argsort()
sort_arr_r = arr[:,sort_row]

print(f'Case1: 2nd row sort\n{sort_arr_r}')

#sort by2nd col
sort_col = arr[:,1].argsort()
sort_arr_c = arr[sort_col,:]

print(f'Case1: 2nd col sort\n{sort_arr_c}')


Original Array: 
[[8 5 7 5 1]
 [8 4 3 5 9]
 [1 2 7 9 7]
 [9 8 6 1 1]
 [8 6 8 3 4]]
Case1: 2nd row sort
[[7 5 5 8 1]
 [3 4 5 8 9]
 [7 2 9 1 7]
 [6 8 1 9 1]
 [8 6 3 8 4]]
Case1: 2nd col sort
[[1 2 7 9 7]
 [8 4 3 5 9]
 [8 5 7 5 1]
 [8 6 8 3 4]
 [9 8 6 1 1]]
